repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=100"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [
          "types-requests",
          "types-PyYAML",
          "types-setuptools",
        ]
        args: [
          "--ignore-missing-imports",
          "--disallow-untyped-defs",
          "--disallow-incomplete-defs",
          "--check-untyped-defs",
          "--warn-redundant-casts",
          "--warn-unused-ignores",
          "--warn-return-any",
          "--no-implicit-optional",
          "--strict-optional",
        ]
        exclude: "tests/"

  # Custom hooks for further code quality checks
  - repo: local
    hooks:
      - id: check-module-docstring
        name: Check module docstring
        entry: python scripts/check_docstrings.py
        language: python
        types: [python]
        exclude: "tests/|__init__.py|setup.py"
        pass_filenames: true
        
      - id: check-missing-init
        name: Check for missing __init__.py files
        entry: python scripts/check_missing_init.py
        language: python
        pass_filenames: false
        always_run: true