version: '3.8'

services:
  # FastAPI application with NVIDIA GPU support
  api:
    image: brevdev/brev-python:3.10-cuda-11.8
    container_name: owl-api
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - BASE_URI=http://finsight.dev/kg/
      - INCLUDE_PROVENANCE=true
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./app:/app
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        python main.py --host 0.0.0.0 --port 8000
      "

  # DePlot service for chart extraction
  deplot:
    image: brevdev/brev-python:3.10-cuda-11.8
    container_name: owl-deplot
    working_dir: /app/deplot
    ports:
      - "8001:8001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./deplot:/app/deplot
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      bash -c "
        git clone https://github.com/google-research/google-research.git &&
        cd google-research &&
        pip install -e 'deplot[dev]' &&
        pip install 'git+https://github.com/google-research/pix2struct@main#egg=pix2struct[dev]' &&
        pip install openai~=0.26.4 scipy~=1.10.0 &&
        cd deplot &&
        python -m pix2struct.demo --model=chart-to-table --port=8001 --host=0.0.0.0
      "

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: owl-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:9.5.1
    container_name: owl-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data: