global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sap_api'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['sap-api:8000']
    
  - job_name: 'sap_proxy'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sap-proxy:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']