global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'owl_api'
    static_configs:
      - targets: ['owl-api:8000']
    metrics_path: '/metrics'

  - job_name: 'triton'
    static_configs:
      - targets: ['triton:8002']
    metrics_path: '/metrics'

  - job_name: 'dcgm_exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']