global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape API service
  - job_name: "owl-api"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "api:8000"
      - source_labels: [__address__]
        target_label: service
        replacement: "api"

  # Scrape Worker service
  - job_name: "owl-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:8000"]
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "worker:8000"
      - source_labels: [__address__]
        target_label: service
        replacement: "worker"

  # Scrape Redis
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape NVIDIA DCGM Exporter
  - job_name: "dcgm-exporter"
    static_configs:
      - targets: ["dcgm-exporter:9400"]
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape Node Exporter (system metrics)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    scrape_timeout: 10s

  # Scrape cAdvisor (container metrics)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s
    scrape_timeout: 10s